// Auto-generated by ODIN™ — Route Registration Reference
// Paste these into your server.ts under the app setup section

import authRoutes from '../routes/auth.routes';
import subscriptionRoutes from '../routes/subscriptions.routes';
import farmRoutes from '../routes/farm.routes';
import payfastRoutes from '../routes/payfast.routes';

app.use('/api/auth', authRoutes);
app.use('/api/subscriptions', subscriptionRoutes);
app.use('/api/farm', farmRoutes);
app.use('/api', payfastRoutes);

